### ISSUE TITLE
make FX section usable on its own

### ISSUE THREAD

**Issue by jjYBdx4IL** [zynaddsubfx/zynaddsubfx#135]
Would be great if one could use the effects applied to an external audio signal, ie. without the internal sound generation/synth part. Maybe have a pseudo synth implementation that just copies the input audio signal.

**Comment by fundamental** [comment]
Plugin versions of the effects already exist.

**Comment by FinishedBz1** [comment]
Can you name those Plugins because I cannot find them?

**Comment by fundamental** [comment]
see https://github.com/zynaddsubfx/zynaddsubfx/tree/master/src/Plugin the plugin names are prefixed with 'Zyn'
