### ISSUE TITLE
Please help fix the gcc bug

### ISSUE THREAD

**Issue by ackelcn** [zynaddsubfx/zynaddsubfx#202]
I find that this workaround is quite interesting:https://github.com/mdavidsaver/epicscorelibs/commit/78d2f20fa8cbc6a357c6340f890f8d3f84e0be84

I have filed a bug report to GCC: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=105997

Would you please provide the details to reproduce the bug? GCC developers can fully fix the problem, if more details are provided.

**Comment by fundamental** [comment]
The comment associated with the GCC workaround commit provides sufficient details for you to investigate the (likely) compiler bug along with versions known to have the desired behavior as well as versions with the undesired behavior. I recommend you take the effort to investigate the issue if you're interested as you appear to be opening a lot of issues related to compilation behavior on various projects.
