### ISSUE TITLE
Consider Changing ALSA_DEVICE to default

### ISSUE THREAD

**Issue by fundamental** [zynaddsubfx/zynaddsubfx#211]
AFAIK with newer distros 'default' may be a more reliable value than 'hw:0'. Though a small amount of investigation may be required.

**Comment by hselasky** [comment]
Works fine under FreeBSD too. Please go ahead!

Maybe we should document those env's you can override for various audio and midi parameters?

**Comment by fundamental** [comment]
Perhaps, though it's a battle to find the right place to document this sort of thing. I just added a note about the env var to the error messages if it doesn't succeed in opening the device.
