### ISSUE TITLE
windows version

### ISSUE THREAD

**Issue by linuxsynth** [zynaddsubfx/zynaddsubfx#212]
hi

where can we download a free windows installer?
I don't understand why I need to pay for an open source project on the official website :(

thx

**Comment by fundamental** [comment]
Open source projects take time to maintain. The tooling is available to build the mainline zyn yourself and there is a long standing vst fork available on kvr.

**Comment by linuxsynth** [comment]
MOTHERFUCKER
GIVE ME WINDOWS INSTALLER

FUCKFACE
