### ISSUE TITLE
LV2 version: Instrument part 1 not saved in Carla - regression.

### ISSUE THREAD

**Issue by Stazed** [zynaddsubfx/zynaddsubfx#213]
Steps to reproduce:

Building the Fltk or Ntk gui from master.

Load any existing Carla project with zyn and an instrument in part 1.
The instrument will be reset to the first instrument in the bank listing, i.e. Arpeggio1.
Any attempt to save another instrument to part 1 will always be reset to the first bank listed item -- Arpeggio1.

Git bisect revealed that the offending commit is: c1953556 ("Implement ZynAddSubFX::loadProgram", 2021-02-05).

Specifically:

In src/Plugin/ZynAddSubFX/ZynAddSubFX.cpp:

Reverting the following changes fixed it for me.

     void loadProgram(uint32_t index) override
     {
      --        setState(nullptr, defaultState);
      ++        //in plugin mode, only the first part is useful
      ++        middleware->pendingSetProgram(0, index);
     }

Just thought I'd let you know since it has been out there a while and I had been running 3.06 from the distro.
I believe this is also an issue for zest gui, as I noticed it several months back when trying it out. But I did not try building zest from the latest master.

**Comment by fundamental** [comment]
Good timing, we're prepping for another release now. I'll try to give this a look to see if there's something obvious to be done to correct the commit and if not I'll revert prior to the release.

**Comment by fundamental** [comment]
The proposed modification has been merged. Let me know if any other action is required, otherwise thanks for locating the bug.
