### ISSUE TITLE
Ubuntu Studio 22.04 ld linking error NTK build.

### ISSUE THREAD

**Issue by Stazed** [zynaddsubfx/zynaddsubfx#214]
Getting a: `collect2: error: ld returned 1 exit status`
and a bunch of: `/usr/bin/ld: /usr/local/lib/libntk_images.so: undefined reference to ...`

The problem occurs from .src/UI/CMakeLists.txt line 91:
    -- `target_link_libraries(zynaddsubfx_gui ${NTK_LIBRARIES} ${NTK_IMAGES_LIBRARIES})`

Reversing the order fixes it:
    ++ `target_link_libraries(zynaddsubfx_gui ${NTK_IMAGES_LIBRARIES} ${NTK_LIBRARIES})`

This linking error seems to only occur on UB Studio. I tested the above order reversal on Manjaro, Fedora 36 and Opensuse Tumbleweed and it works with them as well. Even thought the latter distros properly linked to NTK without the change.

Thanks

**Comment by fundamental** [comment]
Thanks for pointing out the issue. The git HEAD should now have the correct linking order in place.
