### ISSUE TITLE
Is there a reason the release feature isn't being updated 

### ISSUE THREAD

**Issue by luzpaz** [zynaddsubfx/zynaddsubfx#271]
![Screenshot_20231206_113441](https://github.com/zynaddsubfx/zynaddsubfx/assets/4140247/b9938804-3409-4bf6-9113-73e917c4ed16)

![Screenshot_20231206_113552](https://github.com/zynaddsubfx/zynaddsubfx/assets/4140247/b41de882-ba97-460d-9d98-90942c31e905)

**Comment by fundamental** [comment]
We do not use this feature on github and list completed releases elsewhere.

**Comment by luzpaz** [comment]
where are they announced ?

**Comment by fundamental** [comment]
Typically the zynaddsubfx-user mailing list, the linux-audio-announce mailing list, the zynaddsubfx subforum on KVR, the update list for users that have paid binaries, the website is updated to reflect the change notes, and tags are used to show which commits compose a given release.
