### ISSUE TITLE
[Feature Request] Sampler

### ISSUE THREAD

**Issue by super-manis** [zynaddsubfx/zynaddsubfx#286]
Would it be nice to add a sampler inside the synth? This would allow for much more complex sound development like Grand Pianos which require noise samples to work correctly. Adding such thing would make the synth much more versatile combining both the benefits of a ROMpler and a traditional synth.

**Comment by fundamental** [comment]
Adding in sampler functionality would significantly increase the complexity of Zyn. As such it is out-of-scope and I'd recommend using dedicated samplers instead.

**Comment by super-manis** [comment]
But would it be any chance of making the white-noise sample changeable to any sample the user wants? Would that make the synth much more complex?
